---
- name: add ssh key for cloud_user
  authorized_key:
    user: cloud_user
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIqaEGVXOJgkIaBr2iV+tJ1O5ZiPFGdDUqArwwoc0qEU pauljackson@Pauls-Mac-mini.Kawmak-R"