---
- hosts: all
  remote_user: cloud_user
  sudo: yes
  tasks:

- group:
  name: devops
  state: present

- name: create devops user with admin privileges

  user:
    name: devops
    comment: "Devops User"
    uid: 2001
    group: devops
- hosts: www
  user: cloud_user
  sudo: yes
  tasks: 
  - name: add official epel repo
    yum_repository:
      name: epel
      description: "Extra Packages for Enterprise Linux"
      baseurl: "https://download.fedoraproject.org/pub/epel/$releasever/$basearch/"
      gpgcheck: yes
      gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever"

- name: Install EPEL repository
  hosts: all
  become: yes
  tasks:
    - name: Install EPEL release package (RHEL/CentOS 8 and 9)
      dnf:
        name: epel-release
        state: present
      when: ansible_distribution_major_version in ["8", "9"]
      
    


